### ISSUE TITLE
Where to download train&test dataset?

### ISSUE THREAD

**Issue by dypromise** [qxu-gravitate/pokemon-blog#1]
HI, Qxu!
Thanks for sharing your work! I can find label csv file but dont know where to download your image data.

**Comment by qxu-gravitate** [comment]
@dypromise Thank you for pointing this out. The images were not uploaded due to git ignore setting. You can find them here: https://drive.google.com/drive/folders/1Tk9gP4gxiQkZ7_H27nIXtNl9RbF__F30?usp=sharing. I added the link to the readme file.
